---
abstract: 'Perl extension to model fractions'
author:
  - 'Dave Cross, E<lt>dave@mag-sol.comE<gt>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Fraction
provides:
  Number::Fraction:
    file: lib/Number/Fraction.pm
    version: 1.14
requires:
  Carp: 0
  overload: 0
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.14
